### ISSUE TITLE
[BUG] make-samples with rounding triggers error in Merlin

### ISSUE THREAD

**Issue by rydtran** [LLNL/merlin-spellbook#43]
## 🐛 Bug Report

**Describe the bug**
When running make-samples with rounding in a merlin workflow, the following error occurs:

[2023-03-21 11:36:34: INFO] Generating samples...
[2023-03-21 11:36:37: INFO] Generating samples complete!
[2023-03-21 11:36:37: INFO] Loading samples from 'samples.npy'...
[2023-03-21 11:36:37: ERROR] Object arrays cannot be loaded when allow_pickle=False

**To Reproduce**
1. Create a merlin workflow and use the make-samples command with roudning in the "samples" step.
2. Run merlin workflow in dry mode.

**Expected behavior**
Merlin should be able to load the samples.

**Additional context**
When not using the -round option, the workflow is able to load the samples.

I'm using the following packages:

> merlin-spellbook==0.8.1
> merlin==1.8.3 (not using 1.9.1 b/c it is unable to correctly resubmit itself when doing an iterative workflow)

**Command**
spellbook make-samples -dims 6 -n 8 -sample_type lhs -outfile=samples.npy -scale "[[-0.5,0.5],[-0.5,0.5],[430,452],[60,70],[50,60],[0,1]]" -seed 10 -round "[False,False,False,False,False,round]"

**Comment by lucpeterson** [comment]
This was fixed in Merlin PR 398 and is on the develop branch. 

https://github.com/LLNL/merlin/pull/398
